name: Salesforce Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: forcedotcom/sfdx-action@v1

      - name: Authenticate to Salesforce using sfdx-auth-url
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "Authenticating to Salesforce using auth URL..."
          sfdx force:auth:sfdxurl:store --sfdxurlfile $SFDX_AUTH_URL --setdefaultdevhubusername

      - name: Run Validation (Apex tests, etc.)
        run: |
          echo "Running validation..."
          sfdx force:source:deploy -p force-app -u ${{ secrets.SFDX_AUTH_URL }} -w 10
