name: Salesforce Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: forcedotcom/sfdx-action@v1

      - name: Authenticate to Salesforce
        env:
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
        run: |
          echo "Authenticating to Salesforce..."
          sfdx force:auth:password:grant --username $SF_USERNAME --password $SF_PASSWORD --securitytoken $SF_SECURITY_TOKEN --setdefaultdevhubusername

      - name: Run Validation (Apex tests, etc.)
        run: |
          echo "Running validation..."
          sfdx force:source:deploy -p force-app -u $SF_USERNAME -w 10
