name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

     
      - name: Authenticate with Salesforce
        run: |
          echo ${{ secrets.SFDX_AUTH_URL }} | .\sfdx\bin\sfdx force:auth:sfdxurl:store -f - -a MyOrg

      - name: Deploy Metadata
        run: |
          .\sfdx\bin\sfdx force:source:deploy -p force-app
